### ISSUE TITLE
Revisar README

### ISSUE THREAD

**Issue by emedinaa** [isil-pe/AM2-20162-Proyecto-PokemonBattle#1]
Hola ,

Los nombres de los integrantes están juntos, pueden revisar estas guías de markdown https://guides.github.com/features/mastering-markdown/

Saludos

**Comment by darkmaku** [comment]
Estimado profesor,
acabo de hacer el cambio porfavor verifique si esta bien. Estoy atento a sus comentarios y apoyo

**Comment by emedinaa** [comment]
done !
